# Generated by Django 6.0 on 2025-12-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
