# Generated by Django 6.0 on 2025-12-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
